Support setting trigger-chars and set . by default
mattn/efm-langserver pull request #211
Opened 2022-03-24 16:11 UTC by Matts966

- `*` is not a wildcard in `TriggerCharacters`
- Currently only literal `*` triggers completion
- Add `trigger-chars` as setting
- Set `.` by default

2022-03-24 16:40 UTC, mattn requested changes

2022-03-24 16:40 UTC, mattn commented on langserver/handle_initialize.go
> +		h.logger.Println(chars)
Thanks. Please remove this debug code.

2022-03-24 16:41 UTC, mattn commented on langserver/handler.go
> +	triggerChars      *[]string
Please not use pointer.

2022-03-24 16:42 UTC, mattn commented on langserver/handler.go
> +	triggerChars      *[]string
And check with `len(h.triggerChars) > 0` above.

2022-03-24 16:56 UTC, Matts966 commented
Thank you for your review! I removed debug logs and stop using pointer.

2022-04-21 18:05 UTC, merged

2022-04-21 18:05 UTC, mattn commented
Thank you